- name: create a disk
  gcp_compute_disk:
       name: 'disk-instance'
       size_gb: 100
       source_image: 'projects/able-starlight-246507/zones/us-central1-a/diskTypes/pd-ssd'
       zone: "{{ zone }}"
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{{ gcp_cred_file }}"
       scopes:
         - https://www.googleapis.com/auth/compute
       state: present
       type: PERSISTENT
  register: disk
- name: create a network
  gcp_compute_network:
       name: default
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{{ gcp_cred_file }}"
       scopes:
         - https://www.googleapis.com/auth/compute
       state: present
  register: network
- name: create a address
  gcp_compute_address:
       name: 'address-instance'
       region: "{{ region }}"
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{{ gcp_cred_file }}"
       scopes:
         - https://www.googleapis.com/auth/compute
       state: present
  register: address
- name: create an instance
  gcp_compute_instance:
         state: present
         name: instance-1
         machine_type: g1-small
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         metadata:
             ssh-keys: "{{ ssh_keys }}"
         tags:
           items: http-server
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                - name: 'External NAT'
                  nat_ip: "{{ address }}"
                  type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
           - https://www.googleapis.com/auth/devstorage.read_only
           - https://www.googleapis.com/auth/logging.write
           - https://www.googleapis.com/auth/monitoring.write
           - https://www.googleapis.com/auth/servicecontrol
           - https://www.googleapis.com/auth/service.management.readonly
           - https://www.googleapis.com/auth/trace.append
  register: instance
- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=550
- name: Add host to groupname
  add_host: hostname={{ address.address }} groupname=new_instances
